### ISSUE TITLE
ENOTFOUND when running as Docker container

### ISSUE THREAD

**Issue by TekSiDoT** [cschuller/yakjs#57] opened 2017-07-21 06:08 UTC
After initializing the docker container, the following error occurs:

```
user@server:~$ docker logs yakjs
(node:1) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[2017-07-21 05:59:05.920] [INFO] HttpServer.console - .........................................................................
[2017-07-21 05:59:05.920] [INFO] HttpServer.console - YAKjs server initialized and running on http port 8790
[2017-07-21 05:59:05.920] [INFO] HttpServer.console - .........................................................................
[2017-07-21 05:59:05.921] [INFO] HttpServer.console -
[2017-07-21 05:59:05.921] [INFO] HttpServer.console - See ./log/yakjs.log for errors and warnings.
[2017-07-21 05:59:05.921] [INFO] HttpServer.console - Use --debug to display all log messages in the console.
[2017-07-21 05:59:05.921] [INFO] HttpServer.console -
[2017-07-21 05:59:05.921] [INFO] HttpServer.console - Press CTRL + C to stop YAKjs.
[2017-07-21 05:59:30.943] [ERROR] HttpServer.console - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[2017-07-21 05:59:30.943] [ERROR] HttpServer.console - Could not start YAKjs server on http port8790
[2017-07-21 05:59:30.943] [ERROR] HttpServer.console - xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[2017-07-21 05:59:30.943] [ERROR] HttpServer.console -
[2017-07-21 05:59:30.943] [ERROR] HttpServer.console - Error: Unexpected error ENOTFOUND
[2017-07-21 05:59:30.944] [ERROR] HttpServer.console -
[2017-07-21 05:59:30.944] [ERROR] HttpServer.console - See ./log/yakjs.log for more technical details.
```

The port is available and assigned to the container.

Checking logs:
```
...@...:~# more ./log/yakjs.log
./log/yakjs.log: No such file or directory
```

**Comment by cschuller** [comment] 2017-07-21 14:42
Hello TekSiDot!

Thank you for your problem report. 
Currently I am working on YAKjs 3.0 that shall be released in august. 
So it will take some time for me to take a look at this docker issue. 
As an alternative try to use YAKjs with npm install or an "old-school" download ;-)

Hello @dasMulli maybe you can have a look at this docker issue in the meantime?  

BR
Christian

**Comment by TekSiDoT** [comment] 2017-07-21 15:52
Hey there, 

looking forward to seeing YAKjs 3.0 go live! The app is supposed to run on a docker-machine only server, so I'll have to wait for either a fix or 3.0.

LG

Jens

**Comment by dasMulli** [comment] 2017-07-26 20:56
The issue is that it tries to listen on `[::1]` which isn't available when the docker daemon runs without IPv6 support (default AFAIK). (culprit: https://github.com/cschuller/yakjs/blob/f995f813d780e45ad25473920ccfe7bf94bf9395/server/src/expressServer.js#L59)

**Comment by cschuller** [comment] 2017-07-26 21:23
@dasMulli Thank you very much for your quick analysis

What options do we have?
a) disable IPV6 support for YAKjs
b) Command switch thats disable IPV6
c) Different docker config env/setup
d) Different error handling and display a IPV6 problem as warning and not as error

Let's go for (d) now...

**Comment by dasMulli** [comment] 2017-07-27 09:29
(d) is probably the best quick fix.

In the future it may be good to have options to configure the IP/Port for the API interface. probably also through an ENV var which is commonly used in Dockerfiles. Restricting to loopback interfaces is unnecessary for docker containers anyway - listening on all interfaces would be the best option. The question is how to configure it.

**Comment by cschuller** [comment] 2017-07-27 19:47
@TekSiDoT 

**YAKjs 3.0.3 is released.**

Docker is now supported and working fine with YAKjs.  

The docker documentation was updated at
https://github.com/cschuller/yakjs/tree/master/docker

Please create a new yakjs docker image and container to get it up and running.

Feedback and issue reports are highly welcome. 

Grüße in das Weiß-Blaue Land ;-)

**Closed by cschuller** 2017-07-27 19:47 UTC

**Comment by TekSiDoT** [comment] 2017-07-28 06:59
Works like a charm, thank you for your efforts and quick fix!

... Danke und Grüße in die Alpenrepublik ;)

**Comment by dasMulli** [comment] 2017-07-28 09:11
fyi there is an automated build on docker hub that is based on my fork: https://hub.docker.com/r/dasmulli/yak-js/
